name: pr

on: [pull_request]

jobs:
  hadolint:
    uses: wittdennis/pipelines/.github/workflows/hadolint.yaml@4859fcd2398839ffb046803e1686edb94c68d714 # 2.0.33

  build:
    uses: wittdennis/pipelines/.github/workflows/container-image-build.yaml@4859fcd2398839ffb046803e1686edb94c68d714 # 2.0.33
    needs:
      - hadolint
    with:
      image-name: atlantis
      create-artifacts: false
