name: pr

on: [pull_request]

jobs:
  hadolint:
    uses: wittdennis/pipelines/.github/workflows/hadolint.yaml@75a61752f8c76c824a2629cc5ec5bb31236949ce # 2.0.15

  build:
    uses: wittdennis/pipelines/.github/workflows/container-image-build.yaml@75a61752f8c76c824a2629cc5ec5bb31236949ce # 2.0.15
    needs:
      - hadolint
    with:
      image-name: atlantis
      create-artifacts: false
