name: pr

on: [pull_request]

jobs:
  hadolint:
    uses: wittdennis/pipelines/.github/workflows/hadolint.yaml@dc2fa1d2d14e165327e0e58bd1287ca2658fc64e # 2.0.21

  build:
    uses: wittdennis/pipelines/.github/workflows/container-image-build.yaml@dc2fa1d2d14e165327e0e58bd1287ca2658fc64e # 2.0.21
    needs:
      - hadolint
    with:
      image-name: atlantis
      create-artifacts: false
